language: python
cache: pip
dist: bionic

python:
- 3.6
- 3.7
- 3.8

services:
  - postgresql
  - mysql

env:
  global:
    - SECRET_KEY=notaverysecretkey
  jobs:
    - DATABASE=sqlite:///chatbot.sqlite3
    - DATABASE=postgresql://postgres@localhost/chatbot
    - DATABASE=mysql://root@localhost/chatbot

before_install:
- sudo apt-get -qq update

install:
- pip install --upgrade pip setuptools wheel
- pip install -r requirements/dev.txt
- pip install psycopg2-binary mysqlclient
- pip install coveralls

before_script:
- psql -U postgres -c 'CREATE DATABASE chatbot'
- mysql -e 'CREATE DATABASE chatbot'

script:
- pytest --cov

after_success:
- coveralls
