# Generated by Django 3.0.2 on 2020-01-14 15:46

import chat.models
import django.db.models.deletion
import django_extensions.db.fields
import mptt.fields
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='TrainingFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(upload_to=chat.models.training_path)),
            ],
            options={
                'verbose_name': 'TrainingFile',
                'verbose_name_plural': 'TrainingFiles',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chat.Statement')),
                ('training_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='chat.TrainingFile')),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statements',
                'ordering': ('training_file',),
            },
        ),
    ]
