# Generated by Django 3.0.2 on 2020-01-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
    ]
