# Generated by Django 3.0.2 on 2020-02-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='conclusion',
            field=models.TextField(blank=None, default=''),
        ),
    ]
