# Generated by Django 3.0.2 on 2020-02-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_statement_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='redirect',
            field=models.TextField(blank=True, default=''),
        ),
    ]
